# Generated by Django 4.2.9 on 2024-01-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rated_movie',
            new_name='movie',
        ),
    ]
